/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * QuickPizza API
 * QuickPizza is a web application that generates new and exciting pizza combinations.

This API allows you to get random pizza recommendations, rate pizzas, and manage ingredients, tools and other pizza-related data.
 * Service version: 1.0.0
 */
import { URL, URLSearchParams } from 'https://jslib.k6.io/url/1.0.0/index.js'

import http from 'k6/http'
import type { Params, Response } from 'k6/http'

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >
}[keyof T]

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never

type Writable<T> = Pick<T, WritableKeys<T>>
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
    [P in keyof Writable<T>]: T[P] extends object
    ? NonReadonly<NonNullable<T[P]>>
    : T[P]
  }
  : DistributeReadOnlyOverUnions<T>

export interface PizzaRecommendation {
  pizza?: Pizza
  /** Total calories per slice */
  calories?: number
  /** Whether the pizza is vegetarian */
  vegetarian?: boolean
}

export interface Pizza {
  id?: number
  /** @maxLength 64 */
  name?: string
  dough?: Dough
  ingredients?: Ingredient[]
  /** Tool used to make the pizza */
  tool?: string
}

export interface Dough {
  id?: number
  name?: string
  caloriesPerSlice?: number
}

export interface Ingredient {
  id?: number
  name?: string
  caloriesPerSlice?: number
  vegetarian?: boolean
}

export interface Rating {
  readonly id?: number
  /**
   * Rating score (1-5)
   * @minimum 1
   * @maximum 5
   */
  stars: number
  /** ID of the pizza being rated */
  pizza_id: number
}

export interface Restrictions {
  /** Maximum calories per slice */
  maxCaloriesPerSlice?: number
  /** Whether the pizza must be vegetarian */
  mustBeVegetarian?: boolean
  /** Ingredients to exclude */
  excludedIngredients?: string[]
  /** Tools to exclude */
  excludedTools?: string[]
  /** Maximum number of toppings */
  maxNumberOfToppings?: number
  /** Minimum number of toppings */
  minNumberOfToppings?: number
  /**
   * Custom name for the pizza
   * @maxLength 64
   */
  customName?: string
}

export type GetIngredientsByType200 = {
  ingredients?: Ingredient[]
}

export type GetDoughs200 = {
  doughs?: Dough[]
}

export type GetTools200 = {
  tools?: string[]
}

export type GetRatings200 = {
  ratings?: Rating[]
}

export type RegisterUserBody = {
  /** @maxLength 32 */
  username: string
  password: string
}

export type RegisterUser201 = {
  id?: number
  username?: string
}

export type LoginUserParams = {
  /**
   * Whether to set authentication cookie
   */
  set_cookie?: boolean
}

export type LoginUserBody = {
  username: string
  password: string
  csrf?: string
}

export type LoginUser200 = {
  token?: string
}

export type AdminLoginParams = {
  /**
   * Admin username
   */
  user: string
  /**
   * Admin password
   */
  password: string
}

export type AdminLogin200 = {
  token?: string
}

export type GetQuotes200 = {
  quotes?: string[]
}

export type GetNames200 = {
  names?: string[]
}

export type GetAdjectives200 = {
  adjectives?: string[]
}

export type GetConfig200 = { [key: string]: string }

export type GetCookies200Cookies = { [key: string]: string }

export type GetCookies200 = {
  cookies?: GetCookies200Cookies
}

export type SetCookiesParams = {
  /**
   * Cookie name and value (multiple query parameters allowed)
   */
  cookieName?: string
}

export type GetHeaders200Headers = { [key: string]: string }

export type GetHeaders200 = {
  headers?: GetHeaders200Headers
}

export type BasicAuth200 = {
  user?: string
  password?: string
  authenticated?: boolean
}

export type GetJsonParams = {
  /**
   * Any query parameter (multiple allowed)
   */
  param?: string
}

export type GetJson200 = { [key: string]: string }

export type GetXmlParams = {
  /**
   * Any query parameter (multiple allowed)
   */
  param?: string
}

export type GetXml200ParamsItem = {
  key?: string
  value?: string
  index?: number
}

export type GetXml200 = {
  params?: GetXml200ParamsItem[]
}

/**
 * This is the base client to use for interacting with the API.
 */
export class QuickPizzaAPIClient {
  private cleanBaseUrl: string
  private commonRequestParameters: Params

  constructor(clientOptions: {
    baseUrl: string
    commonRequestParameters?: Params
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, '')

    this.commonRequestParameters = clientOptions.commonRequestParameters || {}
  }

  /**
   * Returns a randomly generated pizza with ingredients, tool, and calories
   * @summary Get a pizza recommendation
   */
  getPizzaRecommendation(
    restrictions?: Restrictions,
    requestParameters?: Params
  ): {
    response: Response
    data: PizzaRecommendation
  } {
    const url = new URL(this.cleanBaseUrl + `/api/pizza`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      restrictions ? JSON.stringify(restrictions) : '{}',
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/json',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns a specific pizza recommendation by ID
   * @summary Get a specific pizza recommendation
   */
  getPizzaById(
    id: number,
    requestParameters?: Params
  ): {
    response: Response
    data: Pizza
  } {
    const url = new URL(this.cleanBaseUrl + `/api/pizza/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns ingredients of a specific type (olive_oil, tomato, mozzarella, topping)
   * @summary Get ingredients by type
   */
  getIngredientsByType(
    type: 'olive_oil' | 'tomato' | 'mozzarella' | 'topping',
    requestParameters?: Params
  ): {
    response: Response
    data: GetIngredientsByType200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ingredients/${type}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns all available dough types
   * @summary Get all doughs
   */
  getDoughs(requestParameters?: Params): {
    response: Response
    data: GetDoughs200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/doughs`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns all available pizza-making tools
   * @summary Get all tools
   */
  getTools(requestParameters?: Params): {
    response: Response
    data: GetTools200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/tools`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Record a new pizza rating
   * @summary Create a new rating
   */
  createRating(
    rating: NonReadonly<Rating>,
    requestParameters?: Params
  ): {
    response: Response
    data: Rating
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ratings`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(rating),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/json',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns all ratings made by the current user
   * @summary Get all ratings by user
   */
  getRatings(requestParameters?: Params): {
    response: Response
    data: GetRatings200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ratings`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Delete all ratings for the current user
   * @summary Delete all ratings
   */
  deleteAllRatings(requestParameters?: Params): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ratings`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'DELETE',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Get a specific rating by ID
   * @summary Get a specific rating
   */
  getRatingById(
    id: number,
    requestParameters?: Params
  ): {
    response: Response
    data: Rating
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ratings/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Update an existing rating
   * @summary Update a rating
   */
  updateRating(
    id: number,
    rating: NonReadonly<Rating>,
    requestParameters?: Params
  ): {
    response: Response
    data: Rating
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ratings/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'PUT',
      url.toString(),
      JSON.stringify(rating),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/json',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Partially update an existing rating
   * @summary Partially update a rating
   */
  patchRating(
    id: number,
    rating: NonReadonly<Rating>,
    requestParameters?: Params
  ): {
    response: Response
    data: Rating
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ratings/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'PATCH',
      url.toString(),
      JSON.stringify(rating),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/json',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Delete a rating by ID
   * @summary Delete a rating
   */
  deleteRating(
    id: number,
    requestParameters?: Params
  ): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/ratings/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'DELETE',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Create a new user account
   * @summary Register a new user
   */
  registerUser(
    registerUserBody: RegisterUserBody,
    requestParameters?: Params
  ): {
    response: Response
    data: RegisterUser201
  } {
    const url = new URL(this.cleanBaseUrl + `/api/users`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(registerUserBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/json',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Authenticate a user and receive an auth token
   * @summary User login
   */
  loginUser(
    loginUserBody: LoginUserBody,
    params?: LoginUserParams,
    requestParameters?: Params
  ): {
    response: Response
    data: LoginUser200
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/api/users/token/login` +
      `?${new URLSearchParams(params).toString()}`
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(loginUserBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/json',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Invalidate the user token cookie
   * @summary User logout
   */
  logoutUser(requestParameters?: Params): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/users/token/logout`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Login as an administrator
   * @summary Admin login
   */
  adminLogin(
    params: AdminLoginParams,
    requestParameters?: Params
  ): {
    response: Response
    data: AdminLogin200
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/api/admin/login` +
      `?${new URLSearchParams(params).toString()}`
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request('POST', url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Get a CSRF token for form submissions
   * @summary Get CSRF token
   */
  getCsrfToken(requestParameters?: Params): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/csrf-token`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns a list of pizza-related quotes
   * @summary Get pizza quotes
   */
  getQuotes(requestParameters?: Params): {
    response: Response
    data: GetQuotes200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/quotes`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns a list of classical names for pizza naming
   * @summary Get classical names
   */
  getNames(requestParameters?: Params): {
    response: Response
    data: GetNames200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/names`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns a list of adjectives for pizza naming
   * @summary Get adjectives
   */
  getAdjectives(requestParameters?: Params): {
    response: Response
    data: GetAdjectives200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/adjectives`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Get the current application configuration
   * @summary Get application configuration
   */
  getConfig(requestParameters?: Params): {
    response: Response
    data: GetConfig200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/config`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Check if the application is ready to accept requests
   * @summary Readiness probe
   */
  readinessProbe(requestParameters?: Params): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/ready`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Check if the application is live
   * @summary Liveness probe
   */
  livenessProbe(requestParameters?: Params): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/healthz`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Get Prometheus metrics
   * @summary Prometheus metrics
   */
  getMetrics(requestParameters?: Params): {
    response: Response
    data: string
  } {
    const url = new URL(this.cleanBaseUrl + `/metrics`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the specified HTTP status code. The status code must be between 100 and 599 (inclusive). Any values outside this range will result in a 400 Bad Request response.
   * @summary Return specific status code
   */
  getStatus(
    status: number,
    requestParameters?: Params
  ): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/status/${status}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns n random bytes
   * @summary Get random bytes
   */
  getBytes(
    n: number,
    requestParameters?: Params
  ): {
    response: Response
    data: Blob
  } {
    const url = new URL(this.cleanBaseUrl + `/api/bytes/${n}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request('GET', url.toString(), undefined, {
      ...mergedRequestParameters,
      responseType: 'binary',
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Delays the response for the specified time
   * @summary Delayed response
   */
  getDelay(
    delay: string,
    requestParameters?: Params
  ): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/delay/${delay}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Test endpoint for GET requests
   * @summary Simple GET endpoint
   */
  httpGet(requestParameters?: Params): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/get`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Test endpoint for DELETE requests
   * @summary Simple DELETE endpoint
   */
  httpDelete(requestParameters?: Params): {
    response: Response
    data: void
  } {
    const url = new URL(this.cleanBaseUrl + `/api/delete`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'DELETE',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the POSTed data back in the response
   * @summary Echo POST data
   */
  httpPost(
    httpPostBody: string,
    requestParameters?: Params
  ): {
    response: Response
    data: string
  } {
    const url = new URL(this.cleanBaseUrl + `/api/post`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(httpPostBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': '*/*',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the PUT data back in the response
   * @summary Echo PUT data
   */
  httpPut(
    httpPutBody: string,
    requestParameters?: Params
  ): {
    response: Response
    data: string
  } {
    const url = new URL(this.cleanBaseUrl + `/api/put`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'PUT',
      url.toString(),
      JSON.stringify(httpPutBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': '*/*',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the PATCH data back in the response
   * @summary Echo PATCH data
   */
  httpPatch(
    httpPatchBody: string,
    requestParameters?: Params
  ): {
    response: Response
    data: string
  } {
    const url = new URL(this.cleanBaseUrl + `/api/patch`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'PATCH',
      url.toString(),
      JSON.stringify(httpPatchBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': '*/*',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns all the cookies sent with the request
   * @summary Get cookies
   */
  getCookies(requestParameters?: Params): {
    response: Response
    data: GetCookies200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/cookies`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Sets cookies according to query parameters
   * @summary Set cookies
   */
  setCookies(
    params?: SetCookiesParams,
    requestParameters?: Params
  ): {
    response: Response
    data: void
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/api/cookies` +
      `?${new URLSearchParams(params).toString()}`
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request('POST', url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the headers sent with the request
   * @summary Get request headers
   */
  getHeaders(requestParameters?: Params): {
    response: Response
    data: GetHeaders200
  } {
    const url = new URL(this.cleanBaseUrl + `/api/headers`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Test endpoint for basic auth
   * @summary Basic auth test
   */
  basicAuth(
    username: string,
    password: string,
    requestParameters?: Params
  ): {
    response: Response
    data: BasicAuth200
  } {
    const url = new URL(
      this.cleanBaseUrl + `/api/basic-auth/${username}/${password}`
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the query parameters as JSON
   * @summary Query params as JSON
   */
  getJson(
    params?: GetJsonParams,
    requestParameters?: Params
  ): {
    response: Response
    data: GetJson200
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/api/json` +
      `?${new URLSearchParams(params).toString()}`
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request('GET', url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the query parameters as XML
   * @summary Query params as XML
   */
  getXml(
    params?: GetXmlParams,
    requestParameters?: Params
  ): {
    response: Response
    data: GetXml200
  } {
    const url = new URL(
      this.cleanBaseUrl +
      `/api/xml` +
      `?${new URLSearchParams(params).toString()}`
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request('GET', url.toString(), undefined, {
      ...mergedRequestParameters,
    })
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    }
  }
}
