{
 "title": "K6 - UI - Live",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "testName",
    "label": "Test",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"testName\", predicate: (r) => r.testType == \"K6-UI\")"
    }
   },
   {
    "name": "scenario",
    "label": "Config",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"scenario\", predicate: (r) => r.testType == \"K6-UI\")"
    }
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"release\")"
    }
   },
   {
    "name": "buildId",
    "label": "Build",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"buildId\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "First Contentful Paint (FCP) ",
   "type": "timeseries",
   "description": "First Contentful Paint (FCP) measures the time from when the user first navigated to the page to when any part of the page's content is rendered on the screen. For this metric, \"content\" refers to text, images (including background images), <svg> elements, or non-white <canvas> elements.",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_fcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"browser_web_vital_fcp\")\r\n"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP) ",
   "type": "timeseries",
   "description": "LCP reports the render time of the largest image, text block, or video visible in the viewport, relative to when the user first navigated to the page.",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_lcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"browser_web_vital_lcp\")\r\n"
    }
   ]
  },
  {
   "title": "Cumulative Layout Shift (CLS)",
   "type": "timeseries",
   "description": "Cumulative Layout Shift (CLS) is a stable Core Web Vital metric. It's an important, user-centric metric for measuring visual stability because it helps quantify how often users experience unexpected layout shifts. A low CLS helps ensure that the page is delightful.",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_cls\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"browser_web_vital_cls\")\r\n"
    }
   ]
  },
  {
   "title": "Time to First Byte (TTFB) ",
   "type": "timeseries",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_ttfb\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"browser_web_vital_ttfb\")\r\n"
    }
   ]
  },
  {
   "title": "Content Layer Shift",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "base = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    (r._measurement == \"browser_web_vital_cls\") and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n\r\nmean = base\r\n  |> mean()\r\n  |> map(fn: (r) => ({r with \"avg\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\np75 = base\r\n  |> quantile(q: 0.75, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"p75\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmin = base\r\n  |> min(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"min\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmax = base\r\n  |> max(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"max\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\njoin1 = join(tables: {mean: mean, p75: p75}, on: [\"_measurement\", \"testName\"])\r\njoin2 = join(tables: {joined: join1, min: min}, on: [\"_measurement\", \"testName\"])\r\nfinal = join(tables: {joined: join2, max: max}, on: [\"_measurement\", \"testName\"])\r\n\r\nfinal\r\n  |> rename(columns: {\r\n    _measurement: \"Metric\",\r\n    testName: \"Test Name\",\r\n    avg: \"Avg\",\r\n    p75: \"p(75)\",\r\n    min: \"Min\",\r\n    max: \"Max\"\r\n  })\r\n  |> keep(columns: [\"Test Name\", \"Metric\", \"Avg\", \"p(75)\", \"Min\", \"Max\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"WebVitals\")\r\n"
    }
   ]
  },
  {
   "title": "Web vitals",
   "type": "table",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "base = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    (r._measurement == \"browser_web_vital_fcp\" or\r\n     r._measurement == \"browser_web_vital_lcp\" or\r\n     r._measurement == \"browser_web_vital_ttfb\") and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n\r\nmean = base\r\n  |> mean()\r\n  |> map(fn: (r) => ({r with \"avg\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\np75 = base\r\n  |> quantile(q: 0.75, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"p75\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmin = base\r\n  |> min(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"min\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmax = base\r\n  |> max(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"max\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\njoin1 = join(tables: {mean: mean, p75: p75}, on: [\"_measurement\", \"testName\"])\r\njoin2 = join(tables: {joined: join1, min: min}, on: [\"_measurement\", \"testName\"])\r\nfinal = join(tables: {joined: join2, max: max}, on: [\"_measurement\", \"testName\"])\r\n\r\nfinal\r\n  |> rename(columns: {\r\n    _measurement: \"Metric\",\r\n    testName: \"Test Name\",\r\n    avg: \"Avg\",\r\n    p75: \"p(75)\",\r\n    min: \"Min\",\r\n    max: \"Max\"\r\n  })\r\n  |> keep(columns: [\"Test Name\", \"Metric\", \"Avg\", \"p(75)\", \"Min\", \"Max\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"WebVitals\")\r\n"
    }
   ]
  }
 ]
}