{
 "title": "K6 - UI - Longterm results",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"project\")"
   },
   {
    "name": "testId",
    "label": "Test",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nimport \"strings\"\r\n\r\nschema.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"testid\",\r\n  predicate: (r) => r.project =~ /^${project:regex}$/\r\n)\r\n |> filter(fn: (r) => strings.hasPrefix(v: r._value, prefix: \"K6-UI-\"))\r\n"
    }
   },
   {
    "name": "scenario",
    "label": "Config",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"scenario\")"
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"branch\")"
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"release\")"
    }
   },
   {
    "name": "buildId",
    "label": "Build ID",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"buildId\")"
   }
  ]
 },
 "panels": [
  { "title": "Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "First Contentful Paint (FCP) ",
   "type": "timeseries",
   "description": "First Contentful Paint (FCP) measures the time from when the user first navigated to the page to when any part of the page's content is rendered on the screen. For this metric, \"content\" refers to text, images (including background images), <svg> elements, or non-white <canvas> elements.",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_fcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/\r\n  )\r\n  |> filter(fn: (r) => exists r.uiFeature)\r\n  |> group(columns: [\"uiFeature\"])              // Important: group first\r\n  |> window(every: 1d)                           // Then split into daily windows\r\n  |> quantile(column: \"_value\", q: 0.9, method: \"exact_mean\")\r\n  |> duplicate(column: \"_stop\", as: \"_time\")     // Align _time like aggregateWindow\r\n  |> keep(columns: [\"_time\", \"_value\", \"uiFeature\"])\r\n  |> yield(name: \"fcp_p90_by_uiFeature\")\r\n"
    }
   ]
  },
  {
   "title": "Largest Contentful Paint (LCP) ",
   "type": "timeseries",
   "description": "LCP reports the render time of the largest image, text block, or video visible in the viewport, relative to when the user first navigated to the page.",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_lcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/\r\n  )\r\n  |> filter(fn: (r) => exists r.uiFeature)\r\n  |> group(columns: [\"uiFeature\"])              // group first by uiFeature\r\n  |> window(every: 1d)                           // then window by 1 day\r\n  |> quantile(column: \"_value\", q: 0.9, method: \"exact_mean\")\r\n  |> duplicate(column: \"_stop\", as: \"_time\")     // for visual alignment\r\n  |> keep(columns: [\"_time\", \"_value\", \"uiFeature\"])\r\n  |> yield(name: \"p90_by_uiFeature\")\r\n"
    }
   ]
  },
  {
   "title": "First Input Delay (FID)",
   "type": "timeseries",
   "description": "FID measures the time from when a user first interacts with a page (that is, when they click a link, tap on a button, or use a custom, JavaScript-powered control) to the time when the browser is actually able to begin processing event handlers in response to that interaction.",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_fid\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/\r\n  )\r\n  |> filter(fn: (r) => exists r.uiFeature)\r\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"uiFeature\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"uiFeature\"])\r\n  |> yield(name: \"fid_by_uiFeature\")\r\n"
    }
   ]
  },
  {
   "title": "Time to First Byte (TTFB) ",
   "type": "timeseries",
   "description": "TTFB is a metric that measures the time between the request for a resource and when the first byte of a response begins to arrive.",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_ttfb\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testid\"] =~ /${testId:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/\r\n  )\r\n  |> filter(fn: (r) => exists r.uiFeature)\r\n  |> group(columns: [\"uiFeature\"])              // group before window\r\n  |> window(every: 1d)                           // daily aggregation\r\n  |> quantile(column: \"_value\", q: 0.9, method: \"exact_mean\")\r\n  |> duplicate(column: \"_stop\", as: \"_time\")     // for time alignment\r\n  |> keep(columns: [\"_time\", \"_value\", \"uiFeature\"])\r\n  |> yield(name: \"ttfb_p90_by_uiFeature\")\r\n"
    }
   ]
  }
 ]
}