{
 "title": "K6 - UI - Report One Page Short",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"project\")"
   },
   {
    "name": "testName",
    "label": "Test",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"testName\", predicate: (r) => r.project =~ /^${project:regex}$/ and r.testType == \"K6-UI\")\r\n"
    }
   },
   {
    "name": "scenario",
    "label": "Config",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"scenario\")"
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"release\",\r\n  predicate: (r) => r.project =~ /^${project:regex}$/\r\n)"
    }
   },
   {
    "name": "buildId",
    "label": "Build",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"buildId\")"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Page",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_lcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"scenario\"] =~ /${scenario:regex}/\r\n  )\r\n  |> keep(columns: [\"testName\"])\r\n  |> group()\r\n  |> unique(column: \"testName\")\r\n  |> yield(name: \"testName\")\r\n"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "count_iterations = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_ttfb\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n  |> count(column: \"_value\")\r\n  |> rename(columns: {_value: \"iterations\"})\r\n  |> keep(columns: [\"testName\", \"iterations\"])\r\n  |> yield(name: \"iteration_count\")\r\n"
    }
   ]
  },
  {
   "title": "TTFB",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "p75_fcp = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_ttfb\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n  |> quantile(q: 0.75, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"p75\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n  |> rename(columns: {\r\n    _measurement: \"Metric\",\r\n    testName: \"Test Name\",\r\n    p75: \"p(75)\"\r\n  })\r\n  |> keep(columns: [\"Test Name\", \"Metric\", \"p(75)\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"TTFB_p75\")\r\n"
    }
   ]
  },
  {
   "title": "FCP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "p75_fcp = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_fcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n  |> quantile(q: 0.75, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"p75\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n  |> rename(columns: {\r\n    _measurement: \"Metric\",\r\n    testName: \"Test Name\",\r\n    p75: \"p(75)\"\r\n  })\r\n  |> keep(columns: [\"Test Name\", \"Metric\", \"p(75)\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"FCP_p75\")\r\n"
    }
   ]
  },
  {
   "title": "LCP",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "p75_fcp = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_lcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n  |> quantile(q: 0.75, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"p75\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n  |> rename(columns: {\r\n    _measurement: \"Metric\",\r\n    testName: \"Test Name\",\r\n    p75: \"p(75)\"\r\n  })\r\n  |> keep(columns: [\"Test Name\", \"Metric\", \"p(75)\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"LCP_p75\")\r\n"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_cls\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1d, fn: (column, tables=<-) => quantile(tables: tables, column: column, q: 0.75), createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"p75_cls_by_testName\")"
    }
   ]
  },
  {
   "title": "Web vitals",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_fcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"browser_web_vital_fcp\")"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_lcp\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"browser_web_vital_lcp\")"
    },
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_ttfb\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"project\"] =~ /${project:regex}/ and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"browser_web_vital_ttfb\")"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"browser_web_vital_cls\" and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> aggregateWindow(every: 1d, fn: (column, tables=<-) => quantile(tables: tables, column: column, q: 0.75), createEmpty: false)\r\n  |> group(columns: [\"testName\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"testName\"])\r\n  |> yield(name: \"p90_cls_by_testName\")"
    }
   ]
  },
  {
   "title": "Web vitals",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "base = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    (r._measurement == \"browser_web_vital_fcp\" or\r\n     r._measurement == \"browser_web_vital_lcp\" or\r\n     r._measurement == \"browser_web_vital_ttfb\") and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n\r\nmean = base\r\n  |> mean()\r\n  |> map(fn: (r) => ({r with \"avg\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\np75 = base\r\n  |> quantile(q: 0.75, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"p75\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmin = base\r\n  |> min(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"min\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmax = base\r\n  |> max(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"max\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\njoin1 = join(tables: {mean: mean, p75: p75}, on: [\"_measurement\", \"testName\"])\r\njoin2 = join(tables: {joined: join1, min: min}, on: [\"_measurement\", \"testName\"])\r\nfinal = join(tables: {joined: join2, max: max}, on: [\"_measurement\", \"testName\"])\r\n\r\nfinal\r\n  |> rename(columns: {\r\n    _measurement: \"Metric\",\r\n    testName: \"Test Name\",\r\n    avg: \"Avg\",\r\n    p75: \"p(75)\",\r\n    min: \"Min\",\r\n    max: \"Max\"\r\n  })\r\n  |> keep(columns: [\"Test Name\", \"Metric\", \"Avg\", \"p(75)\", \"Min\", \"Max\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"WebVitals\")\r\n"
    }
   ]
  },
  {
   "title": "CLS",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "base = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    (r._measurement == \"browser_web_vital_cls\") and\r\n    r._field == \"value\" and\r\n    r[\"group\"] != \"::setup\" and\r\n    r[\"release\"] =~ /${release:regex}/ and\r\n    r[\"buildId\"] =~ /${buildId:regex}/ and\r\n    r[\"testName\"] =~ /${testName:regex}/ and\r\n    r[\"project\"] =~ /${project:regex}/\r\n  )\r\n  |> filter(fn: (r) => r[\"testType\"] == \"K6-UI\")\r\n  |> group(columns: [\"_measurement\", \"testName\"])\r\n\r\nmean = base\r\n  |> mean()\r\n  |> map(fn: (r) => ({r with \"avg\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\np75 = base\r\n  |> quantile(q: 0.75, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"p75\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmin = base\r\n  |> min(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"min\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\nmax = base\r\n  |> max(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"max\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_field\"])\r\n\r\njoin1 = join(tables: {mean: mean, p75: p75}, on: [\"_measurement\", \"testName\"])\r\njoin2 = join(tables: {joined: join1, min: min}, on: [\"_measurement\", \"testName\"])\r\nfinal = join(tables: {joined: join2, max: max}, on: [\"_measurement\", \"testName\"])\r\n\r\nfinal\r\n  |> rename(columns: {\r\n    _measurement: \"Metric\",\r\n    testName: \"Test Name\",\r\n    avg: \"Avg\",\r\n    p75: \"p(75)\",\r\n    min: \"Min\",\r\n    max: \"Max\"\r\n  })\r\n  |> keep(columns: [\"Test Name\", \"Metric\", \"Avg\", \"p(75)\", \"Min\", \"Max\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"WebVitals\")\r\n"
    }
   ]
  }
 ]
}