name: k6-by-zippy

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards/ui:/var/lib/grafana/dashboards/ui
      - ./grafana/dashboards/api:/var/lib/grafana/dashboards/api
      - ./grafana/provisioning:/etc/grafana/provisioning

  k6:
    image: custom-k6:latest
    container_name: k6
    depends_on:
      - influxdb
    env_file:
      - ../.env
    environment:
      - ENVIRONMENT=dev
      - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=k6org
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_INSECURE=true
      - K6_INFLUXDB_TOKEN=7xR0mBsyXqBczWNC6alkOa5mskrM2t2UtAuT8Mf28LYdRVDUQikfJyLfJU7HTuroebuzhESxvKg4FryadokJrA==
      - K6_INFLUXDB_PUSH_INTERVAL=1s
      - K6_SYSTEM_TAGS=proto,subproto,status,method,url,name,group,check,error,error_code,tls_version,scenario,service,expected_response,vu,iter
    volumes:
      - ../tests:/tests
      - ../interface:/interface
      - ../helpers:/helpers
      - ../screenshots:/screenshots
    working_dir: /tests
    stdin_open: true
    tty: true
    entrypoint: ["sleep", "infinity"]

  quickpizza:
    image: ghcr.io/grafana/quickpizza-local:latest
    container_name: quickpizza
    ports:
      - "3333:3333"

volumes:
  influxdb-data:
  grafana-data:
