apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    default: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: k6org
      defaultBucket: k6
    secureJsonData:
      token: dgA2prGhuU5v8OuCQaywZnyhwpnJBAXbTcriO8zshMQXn9dzeVMazKVJR1GwrG4Mv24R7LxSyt4JFXPCA1hqqw==
