apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    default: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: k6org
      defaultBucket: k6
    secureJsonData:
      token: L6DkXd9IZDqafqmFng2bcxcizXObNcyubgNpHjXxFm6y0aTYF2d-PVdCafaaqb1gYL5mRLRH9EBmq_RFsvcT-A==
