apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    default: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: k6org
      defaultBucket: k6
    secureJsonData:
      token: n9vDP8ItoB9CxWDBSf7ygQOkuSmqmyQ414jCGJKq4N9xtXJul8LKmqUd46TSyiqkkIJxUpyYM2XcrCt9RN7ZZQ==
