apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    default: true
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: k6org
      defaultBucket: k6
    secureJsonData:
      token: dAhRok872bfaM-zBz7C0XAeNQHfDkHO2rVYyqPReiXfOoPVVpHWvWmQzQppANCmMBVwu3JEqE1JH_DG799NJYA==
