{
 "title": "K6 - API - Live",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"project\")"
   },
   {
    "name": "testName",
    "label": "Test",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"testName\", predicate: (r) => r.project =~ /^${project:regex}$/ and r.testType == \"K6-API\")\r\n"
    }
   },
   {
    "name": "scenario",
    "label": "Config",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"scenario\")"
    }
   },
   {
    "name": "branch",
    "label": "Branch",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"branch\")"
   },
   {
    "name": "release",
    "label": "Release",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"release\")"
    }
   },
   {
    "name": "buildId",
    "label": "Build ID",
    "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(bucket: v.defaultBucket, tag: \"buildId\")"
   }
  ]
 },
 "panels": [
  { "title": "Test", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"vus\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::setup\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::teardown\")\r\n  |> aggregateWindow(every: 1s, fn: max, createEmpty: false)\r\n  |> yield(name: \"vus\")"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_req_failed\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::setup\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::teardown\")\r\n  |> filter(fn: (r) => r[\"release\"] =~ /${release:regex}/)\r\n  |> filter(fn: (r) => r[\"testName\"] =~ /${testName:regex}/)\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r[\"buildId\"] =~ /${buildId:regex}/)\r\n    |> filter(fn: (r) => r[\"branch\"] =~ /${branch:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> group(columns: [\"_measurement\", \"name\"])\r\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")\r\n"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_reqs\")\n  |> filter(fn: (r) => r[\"group\"] != \"::setup\")\n  |> filter(fn: (r) => r[\"group\"] != \"::teardown\")\n  |> filter(fn: (r) => r[\"branch\"] =~ /${branch:regex}/)\n  |> filter(fn: (r) => r[\"release\"] =~ /${release:regex}/)\n  |> filter(fn: (r) => r[\"buildId\"] =~ /${buildId:regex}/)\n  |> filter(fn: (r) => r[\"testName\"] =~ /${testName:regex}/)\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\n  |> group(columns: [\"_measurement\", \"name\"])\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: true)\n  |> yield(name: \"sum\")\n"
    }
   ]
  },
  {
   "title": "API Response time",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r[\"status\"] == \"200\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::setup\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::teardown\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> filter(fn: (r) => r[\"branch\"] =~ /${branch:regex}/)\r\n  |> filter(fn: (r) => r[\"release\"] =~ /${release:regex}/)\r\n  |> filter(fn: (r) => r[\"buildId\"] =~ /${buildId:regex}/)\r\n  |> filter(fn: (r) => r[\"testName\"] =~ /${testName:regex}/)\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> group(columns: [\"_measurement\", \"name\"])\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "EPs statistics",
   "type": "table",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "data = from(bucket: \"k6\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" or r._measurement == \"http_req_failed\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::setup\")\r\n  |> filter(fn: (r) => r[\"group\"] != \"::teardown\")\r\n  |> filter(fn: (r) => r[\"buildId\"] =~ /${buildId:regex}/)\r\n  |> filter(fn: (r) => r[\"release\"] =~ /${release:regex}/)\r\n  |> filter(fn: (r) => r[\"branch\"] =~ /${branch:regex}/)\r\n  |> filter(fn: (r) => r[\"testName\"] =~ /${testName:regex}/)\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /${scenario:regex}/)\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group(columns: [\"name\"])\r\n\r\nquantile_result = data\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> quantile(q: 0.90, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"Percentile 90th (ms)\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_measurement\", \"_field\"])\r\n\r\nmean_result = data\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> mean(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"Avg Request Time (ms)\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_measurement\", \"_field\"])\r\n\r\ncount_result = data\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> count(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"Requests count\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_measurement\", \"_field\"])\r\n\r\nfailure_result = data\r\n  |> filter(fn: (r) => r._measurement == \"http_req_failed\")\r\n  |> sum(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"Failures\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_measurement\", \"_field\"])\r\n\r\np95_result = data\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> quantile(q: 0.95, method: \"exact_mean\")\r\n  |> map(fn: (r) => ({r with \"Percentile 95th (ms)\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_measurement\", \"_field\"])\r\n\r\nlongest_result = data\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> max(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"Longest Request (ms)\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_measurement\", \"_field\"])\r\n\r\nshortest_result = data\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> min(column: \"_value\")\r\n  |> map(fn: (r) => ({r with \"Shortest Request (ms)\": r._value}))\r\n  |> drop(columns: [\"_value\", \"_start\", \"_stop\", \"_measurement\", \"_field\"])\r\n\r\nquantile_mean_join = join(tables: {quantile: quantile_result, mean: mean_result}, on: [\"name\"])\r\nquantile_mean_count_join = join(tables: {quantile_mean: quantile_mean_join, count: count_result}, on: [\"name\"])\r\nfailures_join = join(tables: {quantile_mean_count: quantile_mean_count_join, failures: failure_result}, on: [\"name\"])\r\np95_join = join(tables: {failures_join: failures_join, p95: p95_result}, on: [\"name\"])\r\nlongest_join = join(tables: {p95_join: p95_join, longest: longest_result}, on: [\"name\"])\r\nfinal_result = join(tables: {longest_join: longest_join, shortest: shortest_result}, on: [\"name\"])\r\n\r\nfinal_result\r\n  |> keep(columns: [\"name\", \"Requests count\", \"Percentile 90th (ms)\", \"Avg Request Time (ms)\", \"Failures\", \"Percentile 95th (ms)\", \"Longest Request (ms)\", \"Shortest Request (ms)\"])\r\n  |> group(columns: [])\r\n  |> yield(name: \"request_stats\")"
    }
   ]
  }
 ]
}