/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * Notes API Documentation
 * 
Welcome to the Notes API Documentation. 

This API allows you to manage notes and organize them according to different categories. 

## Features
- Create notes with title and content.
- Categorize notes into different categories.
- Update and delete notes.
- Search notes by title or category.

This API is also utilized as a backend for the [Notes App available here](https://practice.expandtesting.com/notes/app/).



## API Authorization Guide

To use this API, you must first have a valid account on the system and know your email and password. Once you have that information:

Log in to the API using the **login endpoint**. This will provide you with an authentication token that you can use to access the protected resources.

Keep the token safe, as you will need it for subsequent requests.

To authorize your requests, click the "**Authorize**" button on the top right corner of the Swagger UI interface. A dialog box will appear asking you to enter the authentication token.
Enter the token you obtained from the login endpoint and click "**Authorize**".

You are now authorized to use all the protected API endpoints.



If you need help using this API, check out our **video guide and demo**, which are available [here](https://www.youtube.com/watch?v=bQYvS6EEBZc?sub_confirmation=1)

## Contact Information

If you have any questions or feedback, please do not hesitate to contact us via [email](mailto:expand.testing@gmail.com)





 * Service version: 2.0.0
 */
import { URL } from 'https://jslib.k6.io/url/1.0.0/index.js'

import http from 'k6/http'
import type { Params, Response } from 'k6/http'

export type NoteData = {
  id?: string
  title?: string
  description?: string
  completed?: boolean
  created_at?: string
  updated_at?: string
  category?: string
  user_id?: string
}

export interface Note {
  success?: boolean
  status?: number
  message?: string
  data?: NoteData
}

export type SuccessResponse = {
  success?: boolean
  status?: number
  message?: string
}

export type SuccessOneNoteResponseData = {
  id?: string
  title?: string
  description?: string
  completed?: boolean
  created_at?: string
  updated_at?: string
  category?: string
  user_id?: string
}

export type SuccessOneNoteResponse = {
  success?: boolean
  status?: number
  message?: string
  data?: SuccessOneNoteResponseData
}

export type BadRequestResponse = {
  success?: boolean
  status?: number
  message?: string
}

export type UnauthorizedRequestResponse = {
  success?: boolean
  status?: number
  message?: string
}

export type InternalErrorServerResponse = {
  success?: boolean
  status?: number
  message?: string
}

export type PostUsersRegisterBody = {
  /** User's name */
  name: string
  /** User's email address */
  email: string
  /** User's password */
  password: string
}

export type PostUsersRegister201Data = {
  id?: number
  name?: string
  email?: string
}

export type PostUsersRegister201 = {
  success?: boolean
  status?: number
  message?: string
  data?: PostUsersRegister201Data
}

export type PostUsersRegister400 = {
  success?: boolean
  status?: number
  message?: string
}

export type PostUsersLoginBody = {
  /** User email */
  email: string
  /** User password */
  password: string
}

export type PostUsersLogin200Data = {
  id?: string
  email?: string
  name?: string
  token?: string
}

export type PostUsersLogin200 = {
  success?: boolean
  status?: number
  message?: string
  data?: PostUsersLogin200Data
}

export type GetUsersProfile200Data = {
  id?: string
  name?: string
  email?: string
  phone?: string
  company?: string
}

export type GetUsersProfile200 = {
  success?: boolean
  status?: number
  message?: string
  data?: GetUsersProfile200Data
}

export type PatchUsersProfileBody = {
  /** User's name */
  name: string
  /** User's phone number */
  phone?: string
  /** User's company name */
  company?: string
}

export type PatchUsersProfile200Data = {
  id?: string
  name?: string
  email?: string
  phone?: string
  company?: string
}

export type PatchUsersProfile200 = {
  success?: boolean
  status?: number
  message?: string
  data?: PatchUsersProfile200Data
}

export type PostUsersForgotPasswordBody = {
  /** User email */
  email: string
}

export type PostUsersForgotPassword200 = {
  /** Indicates whether the password reset link was sent successfully */
  success?: boolean
  /** HTTP status code */
  status?: number
  /** Success message indicating that the password reset link was sent successfully */
  message?: string
}

export type PostUsersVerifyResetPasswordTokenBody = {
  /** The password reset token received via email */
  token: string
}

export type PostUsersVerifyResetPasswordToken200 = {
  /** Indicates whether the token is valid */
  success?: boolean
  /** HTTP status code */
  status?: number
  /** Success message indicating that the token is valid */
  message?: string
}

export type PostUsersResetPasswordBody = {
  /** The password reset token received via email */
  token: string
  /** The new password for the user's account */
  newPassword: string
}

export type PostUsersResetPassword200 = {
  /** Indicates whether the password reset was successful */
  success?: boolean
  /** HTTP status code */
  status?: number
  /** Success message indicating that the password reset was successful */
  message?: string
}

export type PostUsersChangePasswordBody = {
  /** The current password */
  currentPassword: string
  /** The new password */
  newPassword: string
}

export type PostUsersChangePassword200 = {
  /** Indicates whether the password change was successful */
  success?: boolean
  /** HTTP status code */
  status?: number
  /** Success message indicating that the password change was successful */
  message?: string
}

/**
 * Note category
 */
export type PostNotesBodyCategory =
  (typeof PostNotesBodyCategory)[keyof typeof PostNotesBodyCategory]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostNotesBodyCategory = {
  Home: 'Home',
  Work: 'Work',
  Personal: 'Personal',
} as const

export type PostNotesBody = {
  /** Title of the note */
  title: string
  /** Description of the note */
  description: string
  /** Note category */
  category: PostNotesBodyCategory
}

export type GetNotes200DataItem = {
  id?: string
  title?: string
  description?: string
  category?: string
  completed?: boolean
  created_at?: string
  updated_at?: string
  user_id?: string
}

export type GetNotes200 = {
  success?: boolean
  status?: number
  message?: string
  data?: GetNotes200DataItem[]
}

/**
 * Category of the note ("Home", "Work" or "Personal")
 */
export type PutNotesIdBodyCategory =
  (typeof PutNotesIdBodyCategory)[keyof typeof PutNotesIdBodyCategory]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutNotesIdBodyCategory = {
  Home: 'Home',
  Work: 'Work',
  Personal: 'Personal',
} as const

export type PutNotesIdBody = {
  /** Title of the note */
  title: string
  /** Description of the note */
  description: string
  /** Status of the note (completed or not completed) */
  completed: boolean
  /** Category of the note ("Home", "Work" or "Personal") */
  category: PutNotesIdBodyCategory
}

export type PatchNotesIdBody = {
  /** New value for the `completed` attribute */
  completed: boolean
}

export type PatchNotesId200Data = {
  id?: string
  title?: string
  description?: string
  completed?: boolean
  created_at?: string
  updated_at?: string
  category?: string
  user_id?: string
}

export type PatchNotesId200 = {
  success?: boolean
  status?: number
  message?: string
  data?: PatchNotesId200Data
}

/**
 * This is the base client to use for interacting with the API.
 */
export class NotesAPIDocumentationClient {
  private cleanBaseUrl: string
  private commonRequestParameters: Params

  constructor(clientOptions: {
    baseUrl: string
    commonRequestParameters?: Params
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, '')

    this.commonRequestParameters = clientOptions.commonRequestParameters || {}
  }

  /**
   * Use this API endpoint to check if the server is running and healthy
   * @summary Check the health of the API Notes service
   */
  getHealthCheck(requestParameters?: Params): {
    response: Response
    data: SuccessResponse
  } {
    const url = new URL(this.cleanBaseUrl + `/health-check`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the newly created user object
   * @summary Creates a new user account
   */
  postUsersRegister(
    postUsersRegisterBody: PostUsersRegisterBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PostUsersRegister201
  } {
    const url = new URL(this.cleanBaseUrl + `/users/register`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(postUsersRegisterBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Authenticate a user and return access token
   * @summary Log in as an existing user
   */
  postUsersLogin(
    postUsersLoginBody: PostUsersLoginBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PostUsersLogin200
  } {
    const url = new URL(this.cleanBaseUrl + `/users/login`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(postUsersLoginBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Returns the profile information for the logged-in current user.
   * @summary Retrieve user profile information
   */
  getUsersProfile(requestParameters?: Params): {
    response: Response
    data: GetUsersProfile200
  } {
    const url = new URL(this.cleanBaseUrl + `/users/profile`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Update the user profile information for the logged-in user
   * @summary Update the user profile information
   */
  patchUsersProfile(
    patchUsersProfileBody: PatchUsersProfileBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PatchUsersProfile200
  } {
    const url = new URL(this.cleanBaseUrl + `/users/profile`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'PATCH',
      url.toString(),
      JSON.stringify(patchUsersProfileBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Sends a password reset link to the user's email address, allowing them to reset their password
   * @summary Send password reset link to user's email
   */
  postUsersForgotPassword(
    postUsersForgotPasswordBody: PostUsersForgotPasswordBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PostUsersForgotPassword200
  } {
    const url = new URL(this.cleanBaseUrl + `/users/forgot-password`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(postUsersForgotPasswordBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Verify that the provided password reset token
   * @summary Verify a password reset token
   */
  postUsersVerifyResetPasswordToken(
    postUsersVerifyResetPasswordTokenBody: PostUsersVerifyResetPasswordTokenBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PostUsersVerifyResetPasswordToken200
  } {
    const url = new URL(
      this.cleanBaseUrl + `/users/verify-reset-password-token`
    )
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(postUsersVerifyResetPasswordTokenBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Reset a user's password with a valid password reset token and a new password
   * @summary Reset a user's password
   */
  postUsersResetPassword(
    postUsersResetPasswordBody: PostUsersResetPasswordBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PostUsersResetPassword200
  } {
    const url = new URL(this.cleanBaseUrl + `/users/reset-password`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(postUsersResetPasswordBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Change a user's password by providing the user's current password and the new password.
   * @summary Change a user's password
   */
  postUsersChangePassword(
    postUsersChangePasswordBody: PostUsersChangePasswordBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PostUsersChangePassword200
  } {
    const url = new URL(this.cleanBaseUrl + `/users/change-password`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(postUsersChangePasswordBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Log out the currently authenticated user by invalidating their token.
   * @summary Log out a user
   */
  deleteUsersLogout(requestParameters?: Params): {
    response: Response
    data: SuccessResponse
  } {
    const url = new URL(this.cleanBaseUrl + `/users/logout`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'DELETE',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Deletes the authenticated user account
   * @summary Delete user account
   */
  deleteUsersDeleteAccount(requestParameters?: Params): {
    response: Response
    data: SuccessResponse
  } {
    const url = new URL(this.cleanBaseUrl + `/users/delete-account`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'DELETE',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Creates a new note with the given title, description, category and user id.
   * @summary Create a new note
   */
  postNotes(
    postNotesBody: PostNotesBody,
    requestParameters?: Params
  ): {
    response: Response
    data: SuccessOneNoteResponse
  } {
    const url = new URL(this.cleanBaseUrl + `/notes`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'POST',
      url.toString(),
      JSON.stringify(postNotesBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Retrieve a list of notes for the authenticated user
   * @summary Get all notes
   */
  getNotes(requestParameters?: Params): {
    response: Response
    data: GetNotes200
  } {
    const url = new URL(this.cleanBaseUrl + `/notes`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Retrieve a note by its ID
   * @summary Get a note by ID
   */
  getNotesId(
    id: string,
    requestParameters?: Params
  ): {
    response: Response
    data: SuccessOneNoteResponse
  } {
    const url = new URL(this.cleanBaseUrl + `/notes/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'GET',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Creates a new note with the given title, description, category and user id.
   * @summary Update an existing  note
   */
  putNotesId(
    id: string,
    putNotesIdBody: PutNotesIdBody,
    requestParameters?: Params
  ): {
    response: Response
    data: SuccessOneNoteResponse
  } {
    const url = new URL(this.cleanBaseUrl + `/notes/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'PUT',
      url.toString(),
      JSON.stringify(putNotesIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Update the `completed` attribute of the note with the specified `id`
   * @summary Update the completed status of a note
   */
  patchNotesId(
    id: string,
    patchNotesIdBody: PatchNotesIdBody,
    requestParameters?: Params
  ): {
    response: Response
    data: PatchNotesId200
  } {
    const url = new URL(this.cleanBaseUrl + `/notes/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'PATCH',
      url.toString(),
      JSON.stringify(patchNotesIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Deletes a note with the specified ID.
   * @summary Delete a note by ID
   */
  deleteNotesId(
    id: string,
    requestParameters?: Params
  ): {
    response: Response
    data: SuccessResponse
  } {
    const url = new URL(this.cleanBaseUrl + `/notes/${id}`)
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters
    )
    const response = http.request(
      'DELETE',
      url.toString(),
      undefined,
      mergedRequestParameters
    )
    let data

    try {
      data = response.json()
    } catch {
      data = response.body
    }
    return {
      response,
      data,
    }
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    }
  }
}
